language: "en-US"
reviews:
  path_instructions:
    - path: "**/*.*"
      instructions: |
        Review all files and ensure that:
          - File and directory names must:
            - Be in lowercase
            - Use dashes (-) instead of spaces
            - Use dashes to separate numbers from words (e.g., page-2-content.md)
            - Avoid special characters except dashes
            - Use lowercase file extensions
    - path: "content/**/*.md"
      instructions: |
        Review all markdown files and ensure that:
          - Pinout diagrams are inserted using the pinout shortcode.
          - All lists items that are sentences have a period at the end.
          - Spelling and grammar is correct.
          - Additional valid words are listed in the workspace settings file in the cSpell.words property.
          - Voltages should be described with periods, e.g. 3.3V instead of 3V3.
          - "Arduino Pro Micro" and "SparkFun Pro Micro" should always be called "Pro Micro" instead
    - path: "**/*.svg"
      instructions: |
        Review all SVG files and ensure that:
          - They are minified (using svgo or similar tool to remove comments, whitespace, and unnecessary attributes).
          - They do not contain a viewBox attribute (to ensure consistent scaling behavior).
